"""Initial clean schema from models

Revision ID: 3fcdbd29275e
Revises: 
Create Date: 2025-05-23 22:24:18.605228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3fcdbd29275e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget_plans', 'spent_amount',
               existing_type=mysql.FLOAT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('budget_plans', 'status',
               existing_type=mysql.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.drop_column('budget_plans', 'current_spending')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_plans', sa.Column('current_spending', mysql.FLOAT(), server_default=sa.text("'0'"), nullable=False))
    op.alter_column('budget_plans', 'status',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'ACTIVE'"),
               existing_nullable=False)
    op.alter_column('budget_plans', 'spent_amount',
               existing_type=mysql.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    # ### end Alembic commands ###
