"""Initial clean migration from models

Revision ID: 58c7ad2a5806
Revises: 
Create Date: 2025-05-25 17:29:19.731892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '58c7ad2a5806'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget_plans', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('financial_goals', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('financial_goals', 'start_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('financial_goals', 'target_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('financial_goals', 'priority',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('financial_goals', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_goals', 'status',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('financial_goals', 'priority',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('financial_goals', 'target_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               nullable=True)
    op.alter_column('financial_goals', 'start_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('financial_goals', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('budget_plans', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    # ### end Alembic commands ###
