"""description

Revision ID: ae9824cd1569
Revises: 
Create Date: 2025-05-15 10:17:17.725580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ae9824cd1569'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_transactions', sa.Column('category', sa.String(length=100), nullable=False))
    op.drop_constraint('recurring_transactions_ibfk_2', 'recurring_transactions', type_='foreignkey')
    op.drop_column('recurring_transactions', 'category_id')
    op.add_column('transactions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'category_id')
    op.add_column('recurring_transactions', sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('recurring_transactions_ibfk_2', 'recurring_transactions', 'categories', ['category_id'], ['id'])
    op.drop_column('recurring_transactions', 'category')
    # ### end Alembic commands ###
