"""Add savings plan and projection tables

Revision ID: cdf265fa9a9f
Revises: 03d532a489a7
Create Date: 2025-06-14 00:00:02.561740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cdf265fa9a9f'
down_revision: Union[str, None] = '03d532a489a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_plans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('initial_amount', sa.DECIMAL(precision=18, scale=8), nullable=False, comment='Initial deposit amount'),
    sa.Column('monthly_contribution', sa.DECIMAL(precision=18, scale=8), nullable=False, comment='Monthly contribution amount'),
    sa.Column('interest_rate', sa.DECIMAL(precision=8, scale=4), nullable=False, comment='Annual interest rate as percentage (e.g., 5.25 for 5.25%)'),
    sa.Column('duration_months', sa.Integer(), nullable=False, comment='Duration of the plan in months'),
    sa.Column('interest_type', sa.Enum('SIMPLE', 'COMPOUND', name='interesttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('savings_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_savings_plans_id'), ['id'], unique=False)

    op.create_table('savings_projections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('month_index', sa.Integer(), nullable=False, comment='Month number (0-based index)'),
    sa.Column('balance', sa.DECIMAL(precision=18, scale=8), nullable=False, comment='Total balance at end of month'),
    sa.Column('interest_earned', sa.DECIMAL(precision=18, scale=8), nullable=False, comment='Interest earned this month'),
    sa.ForeignKeyConstraint(['plan_id'], ['savings_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('savings_projections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_savings_projections_id'), ['id'], unique=False)

    with op.batch_alter_table('internal_transfers', schema=None) as batch_op:
        batch_op.drop_index('ix_internal_transfers_from_address')
        batch_op.drop_index('ix_internal_transfers_id')
        batch_op.drop_index('ix_internal_transfers_to_address')
        batch_op.drop_index('ix_internal_transfers_tx_hash')

    op.drop_table('internal_transfers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_transfers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('from_address', mysql.VARCHAR(length=42), nullable=False),
    sa.Column('to_address', mysql.VARCHAR(length=42), nullable=False),
    sa.Column('amount_eth', mysql.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('tx_hash', mysql.VARCHAR(length=66), nullable=True),
    sa.Column('gas_used', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('gas_price', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('internal_transfers', schema=None) as batch_op:
        batch_op.create_index('ix_internal_transfers_tx_hash', ['tx_hash'], unique=False)
        batch_op.create_index('ix_internal_transfers_to_address', ['to_address'], unique=False)
        batch_op.create_index('ix_internal_transfers_id', ['id'], unique=False)
        batch_op.create_index('ix_internal_transfers_from_address', ['from_address'], unique=False)

    with op.batch_alter_table('savings_projections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savings_projections_id'))

    op.drop_table('savings_projections')
    with op.batch_alter_table('savings_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savings_plans_id'))

    op.drop_table('savings_plans')
    # ### end Alembic commands ###
